### ISSUE TITLE
Issue with signature generation

### ISSUE THREAD

**Issue by 1nc0gn170** [starkware-libs/starkex-contracts#9]
Hi team!
   I am trying to sign a message off-chain for `registerEthAddress` function call. I am currently using `ec.starkCurve.sign` to sign the message but it is not working. Docs didn't help, please help me to sign message. 
   
Here is the relavent snippet I am talking about:
https://github.com/starkware-libs/starkex-contracts/blob/0efa9ce324b04226de5dcd7a0139b109bca8f074/scalable-dex/contracts/src/components/Users.sol#L60

Please help

**Comment by 1nc0gn170** [comment]
@gkaempfer @MichaelRiabzev-StarkWare @remollemo Please help

**Comment by 1nc0gn170** [comment]
Resolved Thanks

**Comment by Sidharth1013** [comment]
@1nc0gn170  Could you please tell how you resolved this.
I am getting the INVALID_STARK_KEY error when using this method.

**Comment by 1nc0gn170** [comment]
Hi @Sidharth1013 , 

Here is the script I have written to generate signature:

```js
const { ethers }      = require('ethers');
const starkwareCrypto = require('@starkware-industries/starkware-crypto-utils');
const BigNumber = require('bignumber.js');


const EC_ORDER        = new BigNumber("3618502788666131213697322783095070105526743751716087489154079457884512865583");

const ethKey          = <ETH_KEY>;
const privateKey      = <PRIVATE_KEY>;
const keyPair         = starkwareCrypto.ec.keyFromPrivate(privateKey, 'hex');
const publicKey       = starkwareCrypto.ec.keyFromPublic(
                          keyPair.getPublic(true, 'hex'),
                          'hex'
                        );

const publicKeyX      = publicKey.pub.getX().toString();
const pubYStr         = publicKey.pub.getY().toString();


const msgHash_     = new BigNumber(ethers.utils.solidityKeccak256(["string","address", "uint256"], ["UserRegistration:", ethKey, publicKeyX]));

const msgHash_modulo = msgHash_.mod(EC_ORDER).toString(16);

const {r, s} = starkwareCrypto.sign(keyPair, msgHash_modulo);


console.log("Signature: ", ethers.utils.solidityPack(
  ["uint256","uint256", "uint256"],
  [r.toString(),s.toString(),pubYStr])

```

Feel free to ping, if u still face any difficulties.

**Comment by Sidharth1013** [comment]
Thanks for the response.

I referred to the code snippet you sent. The ethers version I am using is v6 so the method `solidityKeccak256` is migrated to `solidityPackedKeccak256`. On using this method with the inputs defined in your code, I get the error:

Error: Invalid character
```
      const keyPair = getKeyPairFromSignature(signature);
      const publicKey = ec.keyFromPublic(keyPair.getPublic(true, 'hex'), 'hex');

      const publicKeyY = publicKey.pub.getY().toString();
      const publicKeyX = publicKey.pub.getX().toString();

      const msgHash = new BN(
        ethers.solidityPackedKeccak256(
          ['string', 'address', 'uint256'],
          ['UserRegistration:', address, publicKeyX]
        )
      );     // The error is thrown from here
```


```
export function getKeyPairFromSignature(signature) {
  const keySeed = web3.utils.keccak256(String(BigInt(signature)));
  const starkEcOrder = ec.n;
  return ec.keyFromPrivate(grindKey(keySeed, starkEcOrder), 'hex');
}
```

**Comment by Sidharth1013** [comment]
@1nc0gn170  Thanks for your response. I referred to your code snippet but ended up getting the same error. I am using React 18 with RTK 1.9.5, @web3modal/ethers as the Web3Provider, ethers v6 and bn.js for BigNumber utils. Here is my code: 

```
const registerEthAddressWithStarkKey = async () => {
    try {
      const provider = new ethers.BrowserProvider(walletProvider);

      const signer = await provider.getSigner();
      const starkContract = new ethers.Contract(
        starkContractAddress,
        STARKEX_ABI,
        signer
      );

      const keyPair = getKeyPairFromSignature(signature);       //signature from redux store

      const publicKey = ec.keyFromPublic(keyPair.getPublic(true, 'hex'), 'hex');
      const publicKeyX = publicKey.pub.getX().toString();
      const publicKeyY = publicKey.pub.getY().toString();

      const msgHash = new BN(            //BN from bn.js
        removeHexPrefix(
          ethers.solidityPackedKeccak256(
            ['string', 'address', 'uint256'],
            ['UserRegistration:', address, publicKeyX].        //address = ETH ADDRESS from Web3 provider 
          )
        ),
        16
      );

      const maxEcdsaVal = new BN(
        '800000000000000000000000000000000000000000000000000000000000000',
        16
      );

      // Apply modular reduction
      const reducedHashBN = msgHash.mod(maxEcdsaVal);

      // Convert back to hex string
      const reducedHash = '0x' + reducedHashBN.toString(16);

      const {
        signature: { r, s },
      } = signMsgHash(reducedHash);

      const signatureBytes = ethers.solidityPacked(
        ['uint256', 'uint256', 'uint256'],
        [r.toString(), s.toString(), publicKeyY]
      );

      const res = await starkContract.registerEthAddress(
        address,
        publicKeyY,
        signatureBytes
      );
      console.log('RES: ', res);
      return res;
    } catch (error) {
      console.log('ERROR: ', error);
      throw formatEtherErrorMessage(error);
    }
  };
```


This is the error I am getting:
`ERROR:  Error: execution reverted: "INVALID_STARK_KEY" (action="estimateGas", data="0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000011494e56414c49445f535441524b5f4b4559000000000000000000000000000000", reason="INVALID_STARK_KEY", transaction={ "data": "0xbea841870000000000000000000000005ec824648ee920619222d965b60b71673197543300c7078f3e76754cc40eea52fed6e78f9b75244a3073c4dd18527d17ca67eb140000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000006006549f3e695ebe0b959c1e4e0d07a7c139a70b4bedd6a2dbe53d55edaf935fde0254777c554c893989309ec8fb317c2ee09f7307b1c104897fdf02d8c9c6413800c7078f3e76754cc40eea52fed6e78f9b75244a3073c4dd18527d17ca67eb14", "from": "0x5Ec824648ee920619222d965b60B716731975433", "to": "0xA2eC709125Ea693f5522aEfBBC3cb22fb9146B52" }, invocation=null, revert={ "args": [ "INVALID_STARK_KEY" ], "name": "Error", "signature": "Error(string)" }, code=CALL_EXCEPTION, version=6.13.1)`.


If there is any other detail you would like to know, free feel to ping.
Thank you.

**Comment by 1nc0gn170** [comment]
Unfortunately, I used lower version of ethers. I don't have set up to play around now.
